name = "mtls-ocsp"
main = "src/index.js"
compatibility_date = "2023-11-12"
account_id = "<YOUR ACCOUNT>"

workers_dev = false
routes = [{ pattern = "<YOUR APP URL to ENABLE MTLS>", zone_name = "<YOUR ZONE>" },
]

[vars]
CA_CLIENT_ISSUER = "<ISSURE's CERTIFICATE OF YOUR CLIENTS>"

CA_OCSP_ROOT = "<ISSURE's CERTIFICATE OF OCSP RESPONDER>"
